name: Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@bv3

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish